### ISSUE TITLE
Is ForceFocus a set-in-stone name for the widget?

### ISSUE THREAD

**Issue by TomerPacific** [Mosquid/force-focus#1]
Or are you taking suggestions?

**Comment by Mosquid** [comment]
Sure I do. Feel free to offer a better name

**Comment by TomerPacific** [comment]
How about MindAversion?

**Comment by Mosquid** [comment]
IMHO "Aversion" has some negative connotations.

**Comment by TomerPacific** [comment]
The same can be said of **Force**Focus.

How about stayFocused or keepFocus?

**Comment by Mosquid** [comment]
Unfortunately, both of those are already taken by similar chrome extensions :)

Let's brainstorm around "productivity"

**Comment by TomerPacific** [comment]
Are you famliar with the [Pomodoro technique](https://en.wikipedia.org/wiki/Pomodoro_Technique)?

Maybe we can incorporate that into the extension's name.

**Comment by Mosquid** [comment]
Cool. I've never heard of this technique, but apparently, there are [plenty of extensions](https://techwiser.com/pomodoro-chrome-extensions/) offering something related. But it's good. Meaning there's a market for it

**Comment by TomerPacific** [comment]
@Mosquid , so do you want to alter the extension or change the name following my previous comment?

**Comment by Mosquid** [comment]
@TomerPacific I'm totally ok with adding the Pomodoro functionality to the extension and changing the name. Let's zoom about it this week

**Comment by Mosquid** [comment]
@TomerPacific i have a cool name "Traction Control". Traction !== 'Distraction'. What do you think?
